version: "3"

services:

  web:
    image: php:7.2-apache
    container_name: php-z
    restart: unless-stopped
    command: >
      bash -c "a2enmod rewrite
      && apache2-foreground"
    volumes:
      - .:/var/www/html/
    ports:
      - "8080:80"
    networks:
      - default
